feat: added vault client for secrets
bancolombia/secrets-manager pull request #44
Opened 2023-12-28 16:37 UTC by gabheadz

Adds connector for retrieving secrets from Vault.  Solves #42

2023-12-28 17:02 UTC, juancgalvis requested changes
Please review the comments

2024-01-02 10:55 UTC, gabheadz commented on async/vault-async/src/main/java/co/com/bancolombia/secretsmanager/connector/VaultAuthenticator.java
> +                        Mono.error(new SecretException("Error performing authentication with vault: " + response.body())) :
Fixed

2024-01-02 10:57 UTC, gabheadz commented on async/vault-async/src/main/java/co/com/bancolombia/secretsmanager/connector/VaultSecretsManagerConnectorAsync.java
> +                .map(map -> map.getAsJsonObject("data"))
Yes, it corresponds to such payload. Nevertheless I made a change in this particular method to map an actual java class from response.

2024-01-02 17:09 UTC, juancgalvis approved these changes

2024-01-02 17:09 UTC, merged